grafana:
  image:
    repository: loktionovam/grafana
    tag: 5.0.0
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: gitlab-nginx
      kubernetes.io/tls-acme: "true"
      certmanager.k8s.io/issuer: "grafana-issuer"
    labels: {}
    path: /
    hosts:
      - grafana.loktionovam.com
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.loktionovam.com

issuer:
  name: grafana-issuer
  acme:
    email: devops@loktionovam.com
    privateKeySecretRef:
      name: grafana-acme-key
