---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "mongodb_exporter.fullname" . }}
  labels:
    app: search_engine
    component: mongodb_exporter
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search_engine
      component: mongodb_exporter
      release: {{ .Release.Name }}
  template:
    metadata:
      name: mongodb_exporter
      labels:
        app: search_engine
        component: mongodb_exporter
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: mongodb-exporter
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: mongodb-stat
          protocol: TCP
        env:
        - name: MONGODB_URL
          value: {{ .Values.mongodbHost | default (printf "mongodb://%s-mongodb:27017" .Release.Name) }}
